#!/usr/bin/env bash
# Writes a curated, aesthetic ~/.p10k.zsh config
# Design: Two-line prompt, rich right-side info, color-coded git status

cat > "$HOME/.p10k.zsh" << 'ENDOFP10K'
# Generated by zsh-powerup skill — aesthetic + informative p10k config
# Run 'p10k configure' at any time to redo via interactive wizard

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # ── Prompt Layout ───────────────────────────────────────────────────
  # Left prompt segments (line 1 + newline + cursor on line 2)
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # ── Context & System ──
    os_icon               # macOS  / Linux  icon
    context               # user@host (shown when SSH or not default user)

    # ── Directory ──
    dir                   # current directory (truncated nicely)
    dir_writable          # lock icon if not writable

    # ── Git ──
    vcs                   # Full git status (branch, staged, unstaged, untracked, ahead/behind)

    # ── Language / Runtime Versions ──
    node_version          # Node.js version (only in Node project dirs)
    python_version        # Python version (only when .py or venv present)
    go_version            # Go version (only in Go project dirs)
    rust_version          # Rust version (only in Rust project dirs)

    # ── Virtualenv ──
    virtualenv            # Python virtualenv name
    conda_version         # Conda env

    # ── Kubernetes / Cloud ──
    kubecontext           # k8s context (only when kubectl config present)
    aws                   # AWS profile (only when AWS env vars set)

    # ── End of prompt ──
    newline               # ← This creates the two-line prompt
    prompt_char           # ❯ (green=ok, red=error)
  )

  # Right prompt segments (shown on same line as dir/git)
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                # Exit code of last command (shown only on error)
    command_execution_time # How long last command took (shown if >3s)
    background_jobs       # Number of background jobs
    direnv                # Direnv status
    time                  # Current time HH:MM:SS
    battery               # Battery % with icon (macOS/Linux)
  )

  # ── Core Settings ───────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_BACKGROUND=                    # Transparent bg
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'

  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true           # Blank line before prompt

  # ── OS Icon ─────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=212
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='${P9K_CONTENT}'

  # ── Prompt Character ────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

  # ── Directory ───────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  # Special dirs with icons
  local anchor_files=(
    .bzr .citc .git .hg .node-version .python-version
    .ruby-version .shorten_folder_marker .svn .terraform
    CVS Cargo.toml composer.json go.mod package.json
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50

  # ── Git Status ──────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Clean (nothing pending) — bright green
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
  # Modified (unstaged changes) — yellow
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
  # Untracked files — yellow  
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=178
  # Both staged and unstaged — red
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196

  # Show full git info
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
  typeset -g POWERLEVEL9K_VCS_PREFIX='%fon '
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1

  # ── Status (exit code) ──────────────────────────────────────────────
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false                   # Hide when ok
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=70
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=160
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=70
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'

  # ── Command Execution Time ───────────────────────────────────────────
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3      # Show if > 3s
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='%ftook '

  # ── Background Jobs ──────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=37

  # ── Time ─────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=66
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
  typeset -g POWERLEVEL9K_TIME_PREFIX='%fat '

  # ── Battery ──────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=160
  typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=70
  typeset -g POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND=70
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=244
  typeset -g POWERLEVEL9K_BATTERY_STAGES=(
    $'\uf58d' $'\uf579' $'\uf57a' $'\uf57b' $'\uf57c'
    $'\uf57d' $'\uf57e' $'\uf57f' $'\uf580' $'\uf581' $'\uf578'
  )
  typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false

  # ── Node.js Version ───────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_NODE_ICON='\uF898'

  # ── Python Version ────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND=37
  typeset -g POWERLEVEL9K_PYTHON_VERSION_PROJECT_ONLY=true

  # ── Go Version ───────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=37
  typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

  # ── Rust Version ─────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=37
  typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

  # ── Virtualenv ───────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  # ── Conda ────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_CONDA_VERSION_FOREGROUND=37

  # ── Kubernetes Context ────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubie|topgrade'
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*prod*'    PROD
    '*staging*' STAGING
    '*'         DEFAULT
  )
  typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND=196
  typeset -g POWERLEVEL9K_KUBECONTEXT_STAGING_FOREGROUND=214
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=134

  # ── AWS Profile ───────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|cdk|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AWS_CLASSES=(
    '*prod*'    PROD
    '*staging*' STAGING
    '*'         DEFAULT
  )
  typeset -g POWERLEVEL9K_AWS_PROD_FOREGROUND=196
  typeset -g POWERLEVEL9K_AWS_STAGING_FOREGROUND=214
  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=208

  # ── Context (user@host) ───────────────────────────────────────────────
  # Only shown when SSH'd in or running as root/different user
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=227
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=180
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=180
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # ── Instant Prompt ────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # ── Hot Reload ────────────────────────────────────────────────────────
  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
ENDOFP10K

echo "✔ ~/.p10k.zsh written successfully"
